require 'HTTPHeaders'
require 'net/http'
require 'CGI'
require 'nokogiri'
require 'json'

# The EventMachine server for the Card Editor backend
module EditorServer
	def receive_data(data)
		http = HTTPHeaders.new(data)

		methods = EditorServer.instance_methods - Object.instance_methods
		http.request.size.times { STDERR.print "-" }
		STDERR.puts ""
		STDERR.puts http.request
		http.request.size.times { STDERR.print "-" }
		STDERR.puts ""
		if methods.include?(http.url)
			self.send(http.url, http.body)
		else
			self.error("Unknown API call '#{http.url}'")
		end
		http.request.size.times { STDERR.print "-" }
		STDERR.puts ""
	end

	# Respond to missing methods with a sort-of appropriate HTTP response code
	def error(message)
		response = HTTPMethodNotAllowed.new
		response.content = message

		self.send_data(response.to_s)
		STDERR.puts response
	end

	# Utility method for actually saving files
	def save_file(form)
		form["filename"][0] += ".card" if not form["filename"][0] =~ /\.card$/

		builder = Nokogiri::XML::Builder.new do |xml|
			xml << "<!-- Copyright Blazing Griffin 2012 -->"
			xml << "<!-- Generated by CardEditor -->"
			xml.card {
				xml.title {
					xml.cdata(form["title"])
				}
				xml.icon(:atlas => form["icon.atlas"], :key => form["icon.key"])
				xml.image(:atlas => form["image.atlas"], :key => form["image.key"])
				xml.text_ {
					xml.cdata(form["text"])
				}
				xml.tags {
					# Tags
					form.keys.reject { |x| not x =~ /^customTag(\d+)$/ }.each do |tag|
						attrs = {}
						form.keys.reject { |x| not x =~ /^key-#{tag}-(\d+)$/ }.each do |key|
							attrs[form[key][0]] = form[key.gsub(/^key/,"value")][0]
						end
						xml.send(form[tag][0], attrs)
					end

					# Scripts
					form.keys.reject { |x| not (x =~ /^on[A-Z]/ or x == "requires") }.each do |script|
						xml.send(script) {
							xml.cdata(form[script][0])
						} if form[script][0].size > 0
					end
				}
			}
		end

		fout = File.open(File.join("..","cards",form["filename"][0].split("/")),'w')
		fout.puts builder.to_xml
		fout.close
	end

	# Save/Save As entry point
	def save(body)
		# Parse POST data into hash
		form = CGI::parse(body)

		# Save the file
		save_file(form)

		# Send HTTP response
		response = HTTPOK.new
		response["Content-type"] = "text/plain"
		response.content = form["filename"][0] + " saved successfully!"
		self.send_data(response.to_s)
		STDERR.puts response.to_s
	end

	# Load entry point
	def load(body)
		# Parse POST data
		form = CGI::parse(body)

		# Idiotic HACK to get a useable filepath
		if not form["filename"][0] =~ /([a-zA-Z0-0\_\.]+)$/
			error("Can't parse filename \"#{form["filename"][0]}\"")
			return
		end

		filename = $1
		form["filename"][0] = Dir.glob(File.join("..","cards","*",filename))[0]

		# Load the file
		xml = Nokogiri::XML(open(File.join("..","cards",form["filename"][0].split("/"))))
		
		json = {}
		# Filename. Again.
		json["filename"] = form["filename"][0].gsub(/#{File.join("..","cards")}\/?/,"")

		# Metadata
		json["title"] = xml.css("title")[0].content
		icon = xml.css("icon")[0]
		json["icon"] = {"atlas" => icon['atlas'], "key" => icon['key']}
		image = xml.css("image")[0]
		json["image"] = {"atlas" => image['atlas'], "key" => image['key']}
		json["text"] = xml.css("text")[0].content

		# Tags
		tags = []
		xml.xpath("//tags/*").each do |tagnode|
			if tagnode.name =~ /^on[A-Z]/ or tagnode.name =~ /^requires$/
				# Scripts
				json[tagnode.name] = tagnode.content
			else 
				# Tags
				tag = {"name" => tagnode.name}
				tag["attributes"] = tagnode.attributes if tagnode.attributes.size > 0
				tags.push(tag)
			end
		end
		json["tags"] = tags

		# Prepare HTTP response
		response = HTTPOK.new
		response["Content-type"] = "application/json"
		response.content = json.to_json

		# Send HTTP response
		self.send_data(response.to_s)
	end
end